name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Actualiza a la última versión
      - uses: jakejarvis/s3-sync-action@v2  # Actualiza a una versión más reciente si disponible
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: webhost0410
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./main

